kind: Secret
apiVersion: v1
metadata:
  name: party-role-secret
  annotations:
    avp.kubernetes.io/path: "avp/data/party-role"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-avp-test: "secret/party-role/dev"
    vault.hashicorp.com/role: "argocd"
type: Opaque
stringData:
  NODE_ORACLEDB_PASSWORD: <NODE_ORACLEDB_PASSWORD>
  NODE_ORACLEDB_USER: <NODE_ORACLEDB_USER>
  ANYPOINT_MQ_CLIENT_ID: <ANYPOINT_MQ_CLIENT_ID>
  ANYPOINT_MQ_CLIENT_SECRET: <ANYPOINT_MQ_CLIENT_SECRET>
