kind: Secret
apiVersion: v1
metadata:
  name: sample-secret
  annotations:
    avp.kubernetes.io/path: "avp/data/test"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-avp-test: "secret/test"
    vault.hashicorp.com/role: "argocd"
type: Opaque
stringData:
  NODE_ORACLEDB_PASSWORD: <NODE_ORACLEDB_PASSWORD>
  NODE_ORACLEDB_USER: <NODE_ORACLEDB_USER>
